---
version: "2.0"

services:
  osmosis-fe:
    # 1. get the latest tag here https://hub.docker.com/r/osmolabs/osmosis-frontend/tags
    image: osmolabs/osmosis-frontend:370966c
    expose:
      # HTTP
      - port: 3000
        as: 80
        accept:
          - osmosis.decloud.pro
        to:
          - global: true

profiles:
  compute:
    osmosis-fe:
      resources:
        cpu:
          units: 2
        memory:
          size: 2Gi
        storage:
          size: 1Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        osmosis-fe:
          denom: uakt
          amount: 2000

deployment:
  osmosis-fe:
    akash:
      profile: osmosis-fe
      count: 1
